### ISSUE TITLE
*** extconf.rb failed ***

### ISSUE THREAD

**Issue by Akendo** [adrahon/vagrant-kvm#14]
I do have following issue: 

```
  vagrant plugin install vagrant-kvm
  Installing the 'vagrant-kvm' plugin. This can take a few minutes...
  /opt/vagrant/embedded/lib/ruby/1.9.1/rubygems/installer.rb:562:in `rescue in block in build_extensions': ERROR: Failed to build gem native extension. (Gem::Installer::ExtensionBuildError)

          /opt/vagrant/embedded/bin/ruby extconf.rb
  checking for virNetworkPtr in libvirt/libvirt.h... *** extconf.rb failed ***
  Could not create Makefile due to some reason, probably lack of
  necessary libraries and/or headers.  Check the mkmf.log file for more
  details.  You may need configuration options.

  Provided configuration options:
        --with-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/opt/vagrant/embedded/bin/ruby
        --with-libvirt-include
        --without-libvirt-include
        --with-libvirt-lib
        --without-libvirt-lib
        --with-libvirt-config
        --without-libvirt-config
        --with-pkg-config
        --without-pkg-config
  /opt/vagrant/embedded/lib/ruby/1.9.1/mkmf.rb:381:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
  You have to install development tools first.
        from /opt/vagrant/embedded/lib/ruby/1.9.1/mkmf.rb:491:in `block in try_compile'
        from /opt/vagrant/embedded/lib/ruby/1.9.1/mkmf.rb:443:in `with_werror'
        from /opt/vagrant/embedded/lib/ruby/1.9.1/mkmf.rb:491:in `try_compile'
        from /opt/vagrant/embedded/lib/ruby/1.9.1/mkmf.rb:1022:in `try_type'
        from /opt/vagrant/embedded/lib/ruby/1.9.1/mkmf.rb:1050:in `block in have_type'
        from /opt/vagrant/embedded/lib/ruby/1.9.1/mkmf.rb:790:in `block in checking_for'
        from /opt/vagrant/embedded/lib/ruby/1.9.1/mkmf.rb:284:in `block (2 levels) in postpone'
        from /opt/vagrant/embedded/lib/ruby/1.9.1/mkmf.rb:254:in `open'
        from /opt/vagrant/embedded/lib/ruby/1.9.1/mkmf.rb:284:in `block in postpone'
        from /opt/vagrant/embedded/lib/ruby/1.9.1/mkmf.rb:254:in `open'
        from /opt/vagrant/embedded/lib/ruby/1.9.1/mkmf.rb:280:in `postpone'
        from /opt/vagrant/embedded/lib/ruby/1.9.1/mkmf.rb:789:in `checking_for'
        from /opt/vagrant/embedded/lib/ruby/1.9.1/mkmf.rb:1049:in `have_type'
        from extconf.rb:10:in `block in have_libvirt_types'
        from extconf.rb:10:in `each'
        from extconf.rb:10:in `have_libvirt_types'
        from extconf.rb:211:in `<main>'

  Gem files will remain installed in /home/jax/.vagrant.d/gems/gems/ruby-libvirt-0.4.0 for inspection.
        Results logged to /home/jax/.vagrant.d/gems/gems/ruby-libvirt-0.4.0/ext/libvirt/gem_make.out
              from /opt/vagrant/embedded/lib/ruby/1.9.1/rubygems/installer.rb:540:in `block in build_extensions'
              from /opt/vagrant/embedded/lib/ruby/1.9.1/rubygems/installer.rb:515:in `each'
              from /opt/vagrant/embedded/lib/ruby/1.9.1/rubygems/installer.rb:515:in `build_extensions'
              from /opt/vagrant/embedded/lib/ruby/1.9.1/rubygems/installer.rb:180:in `install'
              from /opt/vagrant/embedded/lib/ruby/1.9.1/rubygems/dependency_installer.rb:297:in `block in install'
              from /opt/vagrant/embedded/lib/ruby/1.9.1/rubygems/dependency_installer.rb:270:in `each'
              from /opt/vagrant/embedded/lib/ruby/1.9.1/rubygems/dependency_installer.rb:270:in `each_with_index'
              from /opt/vagrant/embedded/lib/ruby/1.9.1/rubygems/dependency_installer.rb:270:in `install'
              from /opt/vagrant/embedded/gems/gems/vagrant-1.2.2/plugins/commands/plugin/action/install_gem.rb:38:in `block in call'
              from /opt/vagrant/embedded/gems/gems/vagrant-1.2.2/plugins/commands/plugin/gem_helper.rb:42:in `block in with_environment'
              from /opt/vagrant/embedded/lib/ruby/1.9.1/rubygems/user_interaction.rb:40:in `use_ui'
              from /opt/vagrant/embedded/gems/gems/vagrant-1.2.2/plugins/commands/plugin/gem_helper.rb:41:in `with_environment'
              from /opt/vagrant/embedded/gems/gems/vagrant-1.2.2/plugins/commands/plugin/action/install_gem.rb:28:in `call'
              from /opt/vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/action/warden.rb:34:in `call'
              from /opt/vagrant/embedded/gems/gems/vagrant-1.2.2/plugins/commands/plugin/action/bundler_check.rb:20:in `call'
              from /opt/vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/action/warden.rb:34:in `call'
              from /opt/vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/action/builder.rb:116:in `call'
              from /opt/vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/action/runner.rb:61:in `block in run'
              from /opt/vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/util/busy.rb:19:in `busy'
              from /opt/vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/action/runner.rb:61:in `run'
              from /opt/vagrant/embedded/gems/gems/vagrant-1.2.2/plugins/commands/plugin/command/base.rb:17:in `action'
              from /opt/vagrant/embedded/gems/gems/vagrant-1.2.2/plugins/commands/plugin/command/install.rb:44:in `execute'
              from /opt/vagrant/embedded/gems/gems/vagrant-1.2.2/plugins/commands/plugin/command/root.rb:47:in `execute'
              from /opt/vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/cli.rb:46:in `execute'
              from /opt/vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/environment.rb:467:in `cli'
              from /opt/vagrant/embedded/gems/gems/vagrant-1.2.2/bin/vagrant:84:in `<top (required)>'
              from /opt/vagrant/bin/../embedded/gems/bin/vagrant:23:in `load'
              from /opt/vagrant/bin/../embedded/gems/bin/vagrant:23:in `<main>'
```

I serachf or the file:
      ⮀sudo find / -xdev -name libvirt.h
      /usr/include/libvirt/libvirt.h

virNetworkPtr is define inside of the header. ....

any idea?

More info:

`vagrant -v`
`Vagrant version 1.2.2`

`Linux jax 3.9.5-1-ARCH #1 SMP PREEMPT Sat Jun 8 09:22:45 CEST 2013 x86_64 GNU/Linux`

`libvirtd --version
libvirtd (libvirt) 1.0.6`

`qemu 1.5.0-4`

**Comment by electrofelix** [comment]
Hit this problem when installing vagrant-libvirt and it failed to installed ruby-libvirt and discovered that the problem system was missing `pkg-config`. Appears that when pkg-config is missing or possibly also when /usr/lib/pkgconfig/libvirt.pc is missing that the script `ext/libvirt/extconf.rb` from ruby-libvirt is failing to find the headers/libraries but never indicates that the reason is pkg-config being missing.

The hint is that the listed configuration options:

```
  Provided configuration options:
        --with-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/opt/vagrant/embedded/bin/ruby
        --with-libvirt-include
        --without-libvirt-include
        --with-libvirt-lib
        --without-libvirt-lib
        --with-libvirt-config
        --without-libvirt-config
        --with-pkg-config
        --without-pkg-config
```

Has nothing listed for `--with-libvirt-include` or `--with-libvirt-lib`.
