### ISSUE TITLE
Undefined local variable or method `random_mac'

### ISSUE THREAD

**Issue by rosstimson** [adrahon/vagrant-kvm#258]
I cannot `vagrant up` with the kvm plugin on Fedora 20.  My `Vagrantfile` is the default/generated one with the only the following line uncommented:

```
config.vm.network "private_network", ip: "192.168.33.10"
```

The full error I get and a little about my environment is below, please let me know if you need any further details for would like me to do any further troubleshooting steps/tasks.

It's the first time I've attempted to use your plugin so I may be doing something stupid.

```
% vagrant -v
Vagrant 1.6.5

% vagrant plugin list
vagrant-kvm (0.1.9)
vagrant-login (1.0.1, system)
vagrant-mutate (0.3.1)
vagrant-share (1.1.1, system)
```

```
% vagrant up --provider=kvm
Bringing machine 'default' up with 'kvm' provider...
==> default: Importing base box 'freebsd10'...
==> default: Assigning a new mac address to the VM.
==> default: Preparing network interfaces based on configuration...
==> default: Destroying VM and associated drives...
/home/rosstimson/.vagrant.d/gems/gems/vagrant-kvm-0.1.9/lib/vagrant-kvm/action/network.rb:78:in `add_private_network_host': undefined local variable or method `random_mac' for #<VagrantPlugins::ProviderKvm::Action::Network:0x00000002fe6620> (NameError)
    from /home/rosstimson/.vagrant.d/gems/gems/vagrant-kvm-0.1.9/lib/vagrant-kvm/action/network.rb:50:in `block in create_or_update_private_network!'
    from /home/rosstimson/.vagrant.d/gems/gems/vagrant-kvm-0.1.9/lib/vagrant-kvm/action/network.rb:47:in `each'
    from /home/rosstimson/.vagrant.d/gems/gems/vagrant-kvm-0.1.9/lib/vagrant-kvm/action/network.rb:47:in `each_with_index'
    from /home/rosstimson/.vagrant.d/gems/gems/vagrant-kvm-0.1.9/lib/vagrant-kvm/action/network.rb:47:in `create_or_update_private_network!'
    from /home/rosstimson/.vagrant.d/gems/gems/vagrant-kvm-0.1.9/lib/vagrant-kvm/action/network.rb:20:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:34:in `call'
    from /home/rosstimson/.vagrant.d/gems/gems/vagrant-kvm-0.1.9/lib/vagrant-kvm/action/new_mac_address.rb:14:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:34:in `call'
    from /home/rosstimson/.vagrant.d/gems/gems/vagrant-kvm-0.1.9/lib/vagrant-kvm/action/import.rb:106:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:34:in `call'
    from /home/rosstimson/.vagrant.d/gems/gems/vagrant-kvm-0.1.9/lib/vagrant-kvm/action/init_storage_pool.rb:17:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:34:in `call'
    from /home/rosstimson/.vagrant.d/gems/gems/vagrant-kvm-0.1.9/lib/vagrant-kvm/action/customize.rb:39:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:34:in `call'
    from /home/rosstimson/.vagrant.d/gems/gems/vagrant-kvm-0.1.9/lib/vagrant-kvm/action/set_name.rb:49:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/builder.rb:116:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/runner.rb:66:in `block in run'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/util/busy.rb:19:in `busy'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/runner.rb:66:in `run'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/builtin/call.rb:53:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:34:in `call'
    from /home/rosstimson/.vagrant.d/gems/gems/vagrant-kvm-0.1.9/lib/vagrant-kvm/action/init_storage_pool.rb:17:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:34:in `call'
    from /home/rosstimson/.vagrant.d/gems/gems/vagrant-kvm-0.1.9/lib/vagrant-kvm/action/check_kvm.rb:18:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/builder.rb:116:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/runner.rb:66:in `block in run'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/util/busy.rb:19:in `busy'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/runner.rb:66:in `run'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/machine.rb:196:in `action_raw'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/machine.rb:173:in `block in action'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/environment.rb:474:in `lock'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/machine.rb:161:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/machine.rb:161:in `action'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
```

**Comment by pcdummy** [comment]
Having the same problem here:
$ uname -a
Linux ThinkPad-T410 3.16.0-28-generic #38-Ubuntu SMP Sat Dec 13 16:13:28 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

$ ruby -v
ruby 2.1.2p95 (2014-05-08) [x86_64-linux-gnu]

$ vagrant -v
Vagrant 1.7.1

$ vagrant plugin list
vagrant-kvm (0.1.9)
vagrant-lxc (1.0.1)
vagrant-mutate (0.3.1)
vagrant-share (1.1.4, system)

Ubuntu utopic host - apparmor fix not done.

**This is what i did to fix it:**
<pre><code>
vagrant plugin uninstall vagrant-kvm
pushd .
mkdir -p ~/Software
cd ~/Software
git clone https://github.com/adrahon/vagrant-kvm.git
cd vagrant-kvm
./install.rb   # Took ages.
popd
</pre></code>

**Apparmor fix:**
<pre><code>
sudo apt-get install apparmor-utils
sudo aa-complain /usr/lib/libvirt/virt-aa-helper
</pre></code>

**Comment by tzach** [comment]
Thanks @pcdummy 
had the same problem with vagrant-kvm (0.1.9)
installing from git clone solved it

**Comment by acornejo** [comment]
installing through git clone works, but it seems that if you install vagrant-kvm through vagrant (i.e. plugin install), then you get an older version where this bug is still present.
